spring:
  application:
    name: email-sender-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: click&send
      username: brfernandes
      password: senha123

  mail:
    username: clickasend@gmail.com
    password: yxurmzcjckrhljjt
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
    verify:
      host: http://localhost:8081

    default-encoding: UTF-8

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081