spring:
  application:
    name: email-sender-service

  data:
    mongodb:
      uri: mongodb://brfernandes:senha123@localhost:27017/
      host: localhost
      port: 27017
      database: click&send
      username: brfernandes
      password: senha123

  mail:
    username: clickasend@gmail.com
    password: yxurmzcjckrhljjt
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
    verify:
      host: http://localhost:8081

    default-encoding: UTF-8

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Corrigido



server:
  port: 8082